/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export type Category = { 'Food' : null } |
  { 'Electronics' : null } |
  { 'Clothing' : null };
export interface Coupon {
  'discountValue' : bigint,
  'expiryDate' : Timestamp,
  'code' : CouponCode,
  'discountType' : DiscountType,
  'usedCount' : bigint,
  'isActive' : boolean,
  'maxUses' : bigint,
}
export type CouponCode = string;
export interface CouponInput {
  'discountValue' : bigint,
  'expiryDate' : Timestamp,
  'code' : CouponCode,
  'discountType' : DiscountType,
  'isActive' : boolean,
  'maxUses' : bigint,
}
export interface DashboardStats {
  'totalProducts' : bigint,
  'totalOrders' : bigint,
  'pendingOrders' : bigint,
  'totalUsers' : bigint,
  'totalRevenue' : bigint,
  'totalCoupons' : bigint,
}
export type DiscountType = { 'FixedAmount' : null } |
  { 'Percentage' : null };
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'couponCode' : [] | [CouponCode],
  'total' : bigint,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'discount' : bigint,
  'shippingAddress' : ShippingAddress,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'productId' : ProductId,
  'quantity' : bigint,
  'priceAtPurchase' : bigint,
}
export type OrderResult = { 'ok' : Order } |
  { 'err' : string };
export type OrderStatus = { 'Delivered' : null } |
  { 'Cancelled' : null } |
  { 'Processing' : null } |
  { 'Shipped' : null } |
  { 'Pending' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'stockCount' : bigint,
  'category' : Category,
  'image' : ExternalBlob,
  'price' : bigint,
}
export type ProductId = bigint;
export interface ProductInput {
  'name' : string,
  'description' : string,
  'stockCount' : bigint,
  'category' : Category,
  'image' : ExternalBlob,
  'price' : bigint,
}
export interface Review {
  'id' : ReviewId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'comment' : string,
  'rating' : bigint,
}
export type ReviewId = bigint;
export interface ReviewInput {
  'productId' : ProductId,
  'comment' : string,
  'rating' : bigint,
}
export interface ShippingAddress {
  'street' : string,
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'name' : string,
  'state' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WishlistItem { 'productId' : ProductId }
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addReview' : ActorMethod<[ReviewInput], Review>,
  'addToCart' : ActorMethod<[ProductId, bigint], undefined>,
  'addToWishlist' : ActorMethod<[ProductId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCoupon' : ActorMethod<[CouponInput], Coupon>,
  'createOrder' : ActorMethod<
    [Array<CartItem>, [] | [CouponCode], ShippingAddress, string],
    OrderResult
  >,
  'createProduct' : ActorMethod<[ProductInput], Product>,
  'deleteCoupon' : ActorMethod<[CouponCode], boolean>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getProductReviews' : ActorMethod<[ProductId], Array<Review>>,
  'getProducts' : ActorMethod<[[] | [Category]], Array<Product>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getWishlist' : ActorMethod<[], Array<WishlistItem>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[ProductId], undefined>,
  'removeFromWishlist' : ActorMethod<[ProductId], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCoupon' : ActorMethod<[CouponCode, CouponInput], [] | [Coupon]>,
  'updateOrderStatus' : ActorMethod<
    [OrderId, OrderStatus, string],
    [] | [Order]
  >,
  'updateProduct' : ActorMethod<[ProductId, ProductInput], [] | [Product]>,
  'validateCoupon' : ActorMethod<[CouponCode, bigint], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];