/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductId = IDL.Nat;
export const ReviewInput = IDL.Record({
  'productId' : ProductId,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const ReviewId = IDL.Nat;
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Review = IDL.Record({
  'id' : ReviewId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const CouponCode = IDL.Text;
export const DiscountType = IDL.Variant({
  'FixedAmount' : IDL.Null,
  'Percentage' : IDL.Null,
});
export const CouponInput = IDL.Record({
  'discountValue' : IDL.Nat,
  'expiryDate' : Timestamp,
  'code' : CouponCode,
  'discountType' : DiscountType,
  'isActive' : IDL.Bool,
  'maxUses' : IDL.Nat,
});
export const Coupon = IDL.Record({
  'discountValue' : IDL.Nat,
  'expiryDate' : Timestamp,
  'code' : CouponCode,
  'discountType' : DiscountType,
  'usedCount' : IDL.Nat,
  'isActive' : IDL.Bool,
  'maxUses' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const ShippingAddress = IDL.Record({
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'name' : IDL.Text,
  'state' : IDL.Text,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Processing' : IDL.Null,
  'Shipped' : IDL.Null,
  'Pending' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'priceAtPurchase' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'couponCode' : IDL.Opt(CouponCode),
  'total' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'discount' : IDL.Nat,
  'shippingAddress' : ShippingAddress,
  'items' : IDL.Vec(OrderItem),
});
export const OrderResult = IDL.Variant({ 'ok' : Order, 'err' : IDL.Text });
export const Category = IDL.Variant({
  'Food' : IDL.Null,
  'Electronics' : IDL.Null,
  'Clothing' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProductInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stockCount' : IDL.Nat,
  'category' : Category,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'stockCount' : IDL.Nat,
  'category' : Category,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
});
export const DashboardStats = IDL.Record({
  'totalProducts' : IDL.Nat,
  'totalOrders' : IDL.Nat,
  'pendingOrders' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'totalCoupons' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const WishlistItem = IDL.Record({ 'productId' : ProductId });
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addReview' : IDL.Func([ReviewInput], [Review], []),
  'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
  'addToWishlist' : IDL.Func([ProductId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCoupon' : IDL.Func([CouponInput], [Coupon], []),
  'createOrder' : IDL.Func(
      [IDL.Vec(CartItem), IDL.Opt(CouponCode), ShippingAddress, IDL.Text],
      [OrderResult],
      [],
    ),
  'createProduct' : IDL.Func([ProductInput], [Product], []),
  'deleteCoupon' : IDL.Func([CouponCode], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProductReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
  'getProducts' : IDL.Func([IDL.Opt(Category)], [IDL.Vec(Product)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getWishlist' : IDL.Func([], [IDL.Vec(WishlistItem)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromCart' : IDL.Func([ProductId], [], []),
  'removeFromWishlist' : IDL.Func([ProductId], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCoupon' : IDL.Func([CouponCode, CouponInput], [IDL.Opt(Coupon)], []),
  'updateOrderStatus' : IDL.Func(
      [OrderId, OrderStatus, IDL.Text],
      [IDL.Opt(Order)],
      [],
    ),
  'updateProduct' : IDL.Func([ProductId, ProductInput], [IDL.Opt(Product)], []),
  'validateCoupon' : IDL.Func([CouponCode, IDL.Nat], [IDL.Nat], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductId = IDL.Nat;
  const ReviewInput = IDL.Record({
    'productId' : ProductId,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const ReviewId = IDL.Nat;
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Review = IDL.Record({
    'id' : ReviewId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'productId' : ProductId,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const CouponCode = IDL.Text;
  const DiscountType = IDL.Variant({
    'FixedAmount' : IDL.Null,
    'Percentage' : IDL.Null,
  });
  const CouponInput = IDL.Record({
    'discountValue' : IDL.Nat,
    'expiryDate' : Timestamp,
    'code' : CouponCode,
    'discountType' : DiscountType,
    'isActive' : IDL.Bool,
    'maxUses' : IDL.Nat,
  });
  const Coupon = IDL.Record({
    'discountValue' : IDL.Nat,
    'expiryDate' : Timestamp,
    'code' : CouponCode,
    'discountType' : DiscountType,
    'usedCount' : IDL.Nat,
    'isActive' : IDL.Bool,
    'maxUses' : IDL.Nat,
  });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const ShippingAddress = IDL.Record({
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Processing' : IDL.Null,
    'Shipped' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'priceAtPurchase' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'couponCode' : IDL.Opt(CouponCode),
    'total' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'discount' : IDL.Nat,
    'shippingAddress' : ShippingAddress,
    'items' : IDL.Vec(OrderItem),
  });
  const OrderResult = IDL.Variant({ 'ok' : Order, 'err' : IDL.Text });
  const Category = IDL.Variant({
    'Food' : IDL.Null,
    'Electronics' : IDL.Null,
    'Clothing' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProductInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stockCount' : IDL.Nat,
    'category' : Category,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'stockCount' : IDL.Nat,
    'category' : Category,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
  });
  const DashboardStats = IDL.Record({
    'totalProducts' : IDL.Nat,
    'totalOrders' : IDL.Nat,
    'pendingOrders' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'totalCoupons' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const WishlistItem = IDL.Record({ 'productId' : ProductId });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addReview' : IDL.Func([ReviewInput], [Review], []),
    'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
    'addToWishlist' : IDL.Func([ProductId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCoupon' : IDL.Func([CouponInput], [Coupon], []),
    'createOrder' : IDL.Func(
        [IDL.Vec(CartItem), IDL.Opt(CouponCode), ShippingAddress, IDL.Text],
        [OrderResult],
        [],
      ),
    'createProduct' : IDL.Func([ProductInput], [Product], []),
    'deleteCoupon' : IDL.Func([CouponCode], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProductReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
    'getProducts' : IDL.Func(
        [IDL.Opt(Category)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getWishlist' : IDL.Func([], [IDL.Vec(WishlistItem)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromCart' : IDL.Func([ProductId], [], []),
    'removeFromWishlist' : IDL.Func([ProductId], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCoupon' : IDL.Func([CouponCode, CouponInput], [IDL.Opt(Coupon)], []),
    'updateOrderStatus' : IDL.Func(
        [OrderId, OrderStatus, IDL.Text],
        [IDL.Opt(Order)],
        [],
      ),
    'updateProduct' : IDL.Func(
        [ProductId, ProductInput],
        [IDL.Opt(Product)],
        [],
      ),
    'validateCoupon' : IDL.Func([CouponCode, IDL.Nat], [IDL.Nat], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };